### ISSUE TITLE
Geo interface for Browse your data

### ISSUE THREAD

**Issue by StanRonzhin** [PDOK/LinkDaLe#122]
# Description
In the current version the Browse your data tab has a table view, class view, and graph view. 
There is a need for the fourth view - a slippy map based on Leaflet. 
The viewer should show all the things that have coordinates with their label and types. 
Types should be treated as map layers in the layer control. 
Use case: User select and data set from the list. The user can go to map view and see all the data instances.

# ToDo

- [ ] Deploy a slippy map into the map view
- [ ] Develop a SPARQL query that retrieves all instances with coordinates, their types, and labels
- [ ] Transform WKT to GeoJSON with Wicket - Lightweight Javascript for WKT
- [ ] Send types into layer control
