### ISSUE TITLE
Fix pictures in the tutorial to match the text

### ISSUE THREAD

**Issue by StanRonzhin** [PDOK/LinkDaLe#136]
# Description
 - Fix pictures in the tutorial to match the text
# ToDo

- [ ] FInd discrepancies between figures and text in the tutorials
- [ ] Create new figures
- [ ] Update master with new figures
